package grocerywholesaler.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.validation.constraints.NotNull;

/**
 * Produce model
 * Model which JSON inputted into Repository must match
 * Repository collection is "produce"
 * id field auto generated by repository
 * name must be unique
 * name, price, stock not allowed to be null
 */
@Document(collection = "produce")
public class Produce {
    @Id
    private String id;
    @NotNull(message = "Produce name must not be null")
    @Indexed(unique = true)
    private String name;
    @NotNull(message = "Produce price must not be null")
    private double price;
    @NotNull(message = "Produce stock not be null")
    private int stock;
    private String updated;

    public Produce() {
    }

    public Produce(String name, double price, int stock) {
        this.name = name;
        this.price = price;
        this.stock = stock;
    }

    public Produce(String name, double price, int stock, String updated) {
        this.name = name;
        this.price = price;
        this.stock = stock;
        this.updated = updated;
    }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public int getStock() {
        return stock;
    }

    public void setStock(int stock) {
        this.stock = stock;
    }

    public String getUpdated() {
        return updated;
    }

    public void setUpdated(String updated) {
        this.updated = updated;
    }
}
